//
// Generated file, do not edit! Created by opp_msgtool 6.1 from app/HTTPServerMsg.msg.
//

#ifndef __HTTPSERVERMSG_M_H
#define __HTTPSERVERMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class HTTPServerMsg;
/**
 * Class generated from <tt>app/HTTPServerMsg.msg:20</tt> by opp_msgtool.
 * <pre>
 * packet HTTPServerMsg
 * {
 *     string response;
 * }
 * </pre>
 */
class HTTPServerMsg : public ::omnetpp::cPacket
{
  protected:
    omnetpp::opp_string response;

  private:
    void copy(const HTTPServerMsg& other);

  protected:
    bool operator==(const HTTPServerMsg&) = delete;

  public:
    HTTPServerMsg(const char *name=nullptr, short kind=0);
    HTTPServerMsg(const HTTPServerMsg& other);
    virtual ~HTTPServerMsg();
    HTTPServerMsg& operator=(const HTTPServerMsg& other);
    virtual HTTPServerMsg *dup() const override {return new HTTPServerMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getResponse() const;
    virtual void setResponse(const char * response);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const HTTPServerMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, HTTPServerMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline HTTPServerMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<HTTPServerMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __HTTPSERVERMSG_M_H

