//
// Generated file, do not edit! Created by opp_msgtool 6.0 from app/AppMessage.msg.
//

#ifndef __APPMESSAGE_M_H
#define __APPMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class AppMessage;
/**
 * Class generated from <tt>app/AppMessage.msg:20</tt> by opp_msgtool.
 * <pre>
 * packet AppMessage
 * {
 *     int number;
 *     int command;
 * }
 * </pre>
 */
class AppMessage : public ::omnetpp::cPacket
{
  protected:
    int number = 0;
    int command = 0;

  private:
    void copy(const AppMessage& other);

  protected:
    bool operator==(const AppMessage&) = delete;

  public:
    AppMessage(const char *name=nullptr, short kind=0);
    AppMessage(const AppMessage& other);
    virtual ~AppMessage();
    AppMessage& operator=(const AppMessage& other);
    virtual AppMessage *dup() const override {return new AppMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getNumber() const;
    virtual void setNumber(int number);

    virtual int getCommand() const;
    virtual void setCommand(int command);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AppMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AppMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline AppMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<AppMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __APPMESSAGE_M_H

