//
// Generated file, do not edit! Created by opp_msgtool 6.1 from messages/IPDatagram.msg.
//

#ifndef __IPDATAGRAM_M_H
#define __IPDATAGRAM_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class IPDatagram;
// cplusplus {{
   #include "controlInfoIP_m.h"
// }}

#include "controlInfoIP_m.h" // import controlInfoIP

/**
 * Class generated from <tt>messages/IPDatagram.msg:27</tt> by opp_msgtool.
 * <pre>
 * packet IPDatagram extends controlInfoIP
 * {
 *     short protocol;
 *     int ttl;
 *     int payloadLength;
 * }
 * </pre>
 */
class IPDatagram : public ::controlInfoIP
{
  protected:
    short protocol = 0;
    int ttl = 0;
    int payloadLength = 0;

  private:
    void copy(const IPDatagram& other);

  protected:
    bool operator==(const IPDatagram&) = delete;

  public:
    IPDatagram(const char *name=nullptr, short kind=0);
    IPDatagram(const IPDatagram& other);
    virtual ~IPDatagram();
    IPDatagram& operator=(const IPDatagram& other);
    virtual IPDatagram *dup() const override {return new IPDatagram(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual short getProtocol() const;
    virtual void setProtocol(short protocol);

    virtual int getTtl() const;
    virtual void setTtl(int ttl);

    virtual int getPayloadLength() const;
    virtual void setPayloadLength(int payloadLength);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const IPDatagram& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, IPDatagram& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline IPDatagram *fromAnyPtr(any_ptr ptr) { return check_and_cast<IPDatagram*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __IPDATAGRAM_M_H

