//
// Generated file, do not edit! Created by opp_msgtool 6.1 from messages/AlohaFrame.msg.
//

#ifndef __ALOHAFRAME_M_H
#define __ALOHAFRAME_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class AlohaFrame;
// cplusplus {{
   #include "AlohaControlInfo_m.h" 
// }}

#include "AlohaControlInfo_m.h" // import AlohaControlInfo

/**
 * Class generated from <tt>messages/AlohaFrame.msg:27</tt> by opp_msgtool.
 * <pre>
 * packet AlohaFrame extends AlohaControlInfo
 * {
 * }
 * </pre>
 */
class AlohaFrame : public ::AlohaControlInfo
{
  protected:

  private:
    void copy(const AlohaFrame& other);

  protected:
    bool operator==(const AlohaFrame&) = delete;

  public:
    AlohaFrame(const char *name=nullptr, short kind=0);
    AlohaFrame(const AlohaFrame& other);
    virtual ~AlohaFrame();
    AlohaFrame& operator=(const AlohaFrame& other);
    virtual AlohaFrame *dup() const override {return new AlohaFrame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AlohaFrame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AlohaFrame& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline AlohaFrame *fromAnyPtr(any_ptr ptr) { return check_and_cast<AlohaFrame*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __ALOHAFRAME_M_H

